package ihc;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class Codigo extends javax.swing.JFrame {

    Singleton singleton = Singleton.getInstance();
    
    /**
     * Creates new form Codigo
     */
    
    public Codigo() {
        
        initComponents();
        Assembly.setEditable(false);
        Assembly.setBackground(Color.WHITE);
    }
    
    public void printCodigo(String codigo) {
        
        Assembly.setText(codigo);
        Assembly.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AssemblyScroll = new javax.swing.JScrollPane();
        Assembly = new javax.swing.JTextPane();
        Menu = new javax.swing.JMenuBar();
        Arquivo = new javax.swing.JMenu();
        Salvar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compilador");
        setName("Codigo"); // NOI18N

        AssemblyScroll.setViewportView(Assembly);
        TextLineNumber tln = new TextLineNumber(Assembly);

        Arquivo.setText("Arquivo");

        Salvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Salvar.setText("Salvar como");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        Arquivo.add(Salvar);

        Menu.add(Arquivo);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AssemblyScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AssemblyScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );

        AssemblyScroll.setRowHeaderView(tln);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        
        JFileChooser selecionarArquivo;
        selecionarArquivo = new JFileChooser();
	selecionarArquivo.setCurrentDirectory(new java.io.File("."));
        int arquivo = selecionarArquivo.showSaveDialog(null);
        
        if(arquivo == JFileChooser.APPROVE_OPTION) {
                
            try {
                
                singleton.salvarAssembly(selecionarArquivo.getSelectedFile());
                
            } catch (IOException ex) {
                
                Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Arquivo;
    private javax.swing.JTextPane Assembly;
    private javax.swing.JScrollPane AssemblyScroll;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Salvar;
    // End of variables declaration//GEN-END:variables

}
